### PR TITLE
Added support for anchoring through WeakAuras

### PR DESCRIPTION
**Pull request by rootkit1337tv**

### CODE REVIEW

**Comment by sfmict** [comment]
Hi, if you want to use the bar, you should use `HidingBarAddon.bar[1]` or `HidingBarAddon.defaultBar` or `HidingBarAddon.barByName["bar name"]`
"HidingBarBar" will be overwritten when a new bar is created.

**Comment by rootkit1337tv** [comment]
My plan was to anchor the bar to a specific frame in ElvUI so when i change scaling it will stick to that frame and not be out of place, giving the Frame a name seemed to work for me, using the fields you mentioned above does not.

**Comment by rootkit1337tv** [comment]
I assume you cant anchor the bar in settings?

**Comment by sfmict** [comment]
If the bar have a global name then wow ui saves the frame position, if I disable it then your script won't be work. You need to hook UI_SCALE_CHANGED and replace anchors after it.

**Pull request closed without merging**
